services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    command: npm run dev
    volumes:
      - ./server/src/:/app/src/
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src/:/app/src/
